config/routes.rb
SampleApp2::Application.routes.draw do

  resources :users
  resources :sessions, :only => [:new, :create, :destroy]

  match '/home', :to => 'pages#home'
  match 'contact', :to => 'pages#contact'
  match '/about', :to => "pages#about"
  match '/help', :to => "pages#help"
  match '/sign_in', :to => 'pages#sign_in'
  match "/signup", :to => "users#new"
  match '/signin', :to => "sessions#new"
  match '/signout', :to => "sessions#destroy"
  

  root :to => "pages#home"

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  email      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

require 'digest'
class User < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 2
  
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, :presence => true,
                   :length => {:maximum => 20}
  validates :email, :presence => true,
                    :format => {:with => email_regex},
                    :uniqueness => {:case_sensitive => false}
  validates :password, :presence => true,
                      :confirmation => true,
                      :length => {:within => 6..40}

  before_save :encrypt_password
  
  
  def has_password?(submitted_password)
    ap encrypted_password
    ap encrypt(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_by_salt(id, salt)
    user = find_by_id(id)
    user && user.salt == salt ? user : nil
  end

  
  private
    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)      
    end
    
    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end
    
    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end
    
    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"    
  end
  
  def help
    @title = "Help"
  end
  
  def sign_in
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @title = "Sign in"
  end
  
  def create
    ap params
    user = User.authenticate(params[:session][:email], params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid email/password combination."
      @title = "Sign in"
      render 'new'    
    else
      signin user
      return_back_or user
    end
  end
  
  def destroy
    signout
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update, :index]
  before_filter :correct_user, :only => [:edit, :update]
  before_filter :admin_user,   :only => :destroy
  
  def index
    @title = "All users"
    @users = User.paginate(:page => params[:page])
  end
  
  def new
    @user = User.new
    @title = "Sign up"
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      @title = "Sign up"
      render :new
      # redirect_to :action => :new
    end
  end
  
  def show
    @user = User.find(params[:id])
    @title = @user.name
  end
  
  def edit
    @title = "Edit user"
  end
  
  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @title = "Edit user"
      render :edit
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end
  
  private
    def authenticate
      deny_access unless signed_in?
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user? @user
    end
    
    def admin_user
      redirect_to root_path unless current_user.admin?
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag("rails.png", :alt => "logo", :class => "round")
  end
  def title
    @title.present? ? " | " + @title : ""
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def signin user
    @current_user = user
    cookies.permanent.signed[:signin_user] = [user.id, user.salt]
  end
  
  def signout
    current_user = nil
    cookies.delete(:signin_user)
  end
  
  def signed_in?
    current_user.present?
  end
  
  def current_user
    @current_user || user_from_cookie
  end
  
  def current_user= user
    @current_user = user
  end
  
  def user_from_cookie
    id, salt = id_salt_from_cookie
    User.authenticate_by_salt(id, salt)
  end
  
  def id_salt_from_cookie
    cookies.signed[:signin_user] || [nil, nil]
  end
  
  def deny_access
    store_location
    redirect_to signin_path, :notice => "Please sign in first"
  end
  
  def current_user? user
    current_user == user
  end
  
  def return_back_or(default)
    redirect_to (session[:return_to] || default)
    clear_return_to
  end
  
  private
  
  def store_location
    session[:return_to] = request.fullpath
  end
  
  def clear_return_to
    session[:return_to] = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {:size => 50})
    gravatar_image_tag(user.email.downcase, 
                      :class => "gravatar",
                      :gravatar => options)
  end
end

app/views/layouts/_footer.haml
%footer
  %nav.round
    %ul
      %li= link_to "About", about_path
      %li= link_to "Contact", contact_path

= debug(params) if Rails.env.development?

app/views/layouts/_header.haml
%header
  = link_to logo, root_path
  %nav.round
    %ul
      %li= link_to "Home",  home_path
      - if signed_in?
        %li= link_to "Profile", current_user
        %li= link_to "Users", users_path
        %li= link_to "Setting", edit_user_path(current_user)
        
      %li= link_to "Help",  help_path
      - if signed_in?
        %li= link_to "Sign out", signout_path
      - else
        %li= link_to "Sign in", signin_path

app/views/layouts/application.haml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 

%html
  %head
    %title "Ruby on Rails Tutorial Sample App#{title}"
    = csrf_meta_tag
    = stylesheet_link_tag :all
    = javascript_include_tag :defaults
    = stylesheet_link_tag 'custom'

  %body
    .container
      = render "layouts/header"
      %section.round        
        - flash.each do |key, value| 
          .flash{:class => key}= value
        = yield
      = render "layouts/footer"  

app/views/pages/home.haml
%h1 Dou Shen

%p
  This is the home page for the
  = link_to "Ruby on Rails Tutorial", "http://railstutorial.org/" 
  sample application.

= link_to "Sign up now!", signup_path, :class => "signup_button round"

app/views/shared/_error_messages.haml
- if @user.errors.any?
  #error_explanation
    %h2 #{pluralize(object.errors.count, "error")} prohibited this #{object.class.to_s.underscore.humanize.downcase} from being saved:
    %p There were problems with the following fields:
    %ul
      - object.errors.full_messages.each do |msg|
        %li= msg
        
    

app/views/users/_user.haml
%li #{gravatar_for user, :size => 30}, #{link_to user.name, user}
-if current_user.admin?
  %li= link_to "Delete", user, :method => :delete, :confirm => "Are you sure?", :title => "Delete #{user.name}"

app/views/users/_user_form.haml
= render 'shared/error_messages', :object => f.object
= field_set_tag do
  = f.label :name
  = f.text_field :name
= field_set_tag do
  = f.label :email
  = f.text_field :email
= field_set_tag do
  = f.label :password
  = f.password_field :password
= field_set_tag do
  = f.label :password_confirmation
  = f.password_field :password_confirmation
  

app/views/users/edit.haml
%h1 Edit user
= form_for @user do |f|
  = render 'user_form', :f => f
  = field_set_tag do
    = f.submit "Update"


#avatar
  = gravatar_for @user
  = link_to "change", "http://gravatar.com/emails"

-# = form_tag :url => {:action => :create} do
-#   = field_set_tag do
-#     = label :name
-#     = text_field :user_name

app/views/users/index.haml
%h2 All users

= will_paginate @users

%ul.users
  = render @users
= will_paginate @users
= page_entries_info @users

app/views/users/new.haml
%h1 Signup
= form_for @user do |f|
  = render 'user_form', :f => f
  = field_set_tag do
    = f.submit

app/views/users/show.haml
.profile
  .main
    %h1
      = gravatar_for @user
      = @user.name

  .sidebar.round
    %br
    %br
    %strong Name 
    #{@user.name}
    %br
    %strong URL 
    #{@user.email}
    
.clear  